<<<<<<< HEAD
# Generated by Django 4.0 on 2021-12-18 19:55
=======
# Generated by Django 3.2.5 on 2021-12-17 22:10
>>>>>>> 6fa2da8c6d3a16dad38bb76ac4edd17bbed6d93b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=220),
        ),
    ]
