# Generated by Django 3.2.9 on 2021-12-11 18:21

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stationes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=255)),
                ('map', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='RoutesStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.routes')),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.stationes')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Rate', models.IntegerField(default=0)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.buses')),
            ],
        ),
        migrations.AddField(
            model_name='buses',
            name='Route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.routes'),
        ),
    ]
