# Generated by Django 4.0 on 2021-12-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('ubusAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='routesstation',
            name='Route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.routes'),
        ),
        migrations.AddField(
            model_name='routesstation',
            name='Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.stationes'),
        ),
        migrations.AddField(
            model_name='driver',
            name='Bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.buses'),
        ),
        migrations.AddField(
            model_name='buses',
            name='Route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubusAPI.routes'),
        ),
    ]
