# Generated by Django 3.2.9 on 2021-12-11 18:32

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('ubusAPI', '0002_userticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationes',
            old_name='map',
            new_name='locationStation',
        ),
        migrations.AddField(
            model_name='buses',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='buses',
            name='locationBus',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
        ),
    ]
