# Generated by Django 3.2.9 on 2021-12-15 15:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
