# Generated by Django 3.2.9 on 2021-12-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='country',
        ),
    ]
